const allCat = [
  {
    _id: "634ec28efff953ad9c30dd77",
    id: 1,
    name: "Лорд",
    favourite: false,
    rate: 7,
    age: 6,
    description: "Лорд – белый и пушистый с голубыми глазками",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/4-35.jpg",
    __v: 0,
  },
  {
    _id: "634ec3effff953ad9c30ddb8",
    id: 2,
    name: "Рыжик",
    favourite: false,
    rate: 10,
    age: 3,
    description: " Рыжик - внимательный, активный и ласковый.",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/0-70.jpg",
    __v: 0,
  },
  {
    _id: "634ec426fff953ad9c30ddc4",
    id: 3,
    name: "Серко",
    favourite: false,
    rate: 10,
    age: 9,
    description: "Серко любит лесенки, канаты, очень активный и ласковый кот",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/2-34.jpg",
    __v: 0,
  },
  {
    _id: "634ec471fff953ad9c30ddd7",
    id: 4,
    name: "Алиса",
    favourite: false,
    rate: 8,
    age: 4,
    description:
      "Алиса обладает мягким и добрым характером. Очень любит всевозможные лакомства и вкусно покушать.",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/2-51.jpg",
    __v: 0,
  },
  {
    _id: "634ec47cfff953ad9c30dddb",
    id: 5,
    name: "Князь",
    favourite: true,
    rate: 8,
    age: 7,
    description:
      "Князь очень добрый кот, ладит с другими животными, приучен к лотку и когтеточке",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/3-45.jpg",
    __v: 0,
  },
  {
    _id: "634ec485fff953ad9c30dddf",
    id: 6,
    name: "Лисичка",
    favourite: false,
    rate: 9,
    age: 6,
    description:
      "Прелестная Лисичка – трогательная, добродушная и очень-очень общительная девочка.",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/51.jpg",
    __v: 0,
  },
  {
    _id: "634ec48dfff953ad9c30dde2",
    id: 7,
    name: "Ягодка",
    favourite: true,
    rate: 9,
    age: 5,
    description:
      "Ягодке около 5 лет с небольшим, здорова, привита, стерилизована. Лоточек и когтеточку знает прекрасно.",
    img_link:
      "https://bipbap.ru/wp-content/uploads/2017/08/84622314_4451748_N7149274.jpg",
    __v: 0,
  },
  {
    _id: "634ec496fff953ad9c30dde5",
    id: 8,
    name: "Бруно",
    favourite: false,
    rate: 10,
    age: 3,
    description:
      "Очаровательный активный кот Бруно, находится в постоянном движении! Очаровательный и ласковый кот.",
    img_link: "https://bipbap.ru/wp-content/uploads/2017/08/283879099.jpg",
    __v: 0,
  },
  {
    _id: "634ec49efff953ad9c30ddea",
    id: 9,
    name: "Зинка",
    favourite: true,
    rate: 9,
    age: 9,
    description:
      "Немного боязливая, но очень добрая и нежная кошка. Приучена к лотку и когтеточке.",
    img_link:
      "https://bipbap.ru/wp-content/uploads/2017/08/blue_eyes-1024x640.jpg",
    __v: 0,
  },
];
